{-# LANGUAGE OverloadedStrings #-}

import AoC
import Data.Char (isAlpha, isDigit)
import Data.List (transpose)
import Data.Map (Map, filterWithKey, fromList, keys, lookup, (!))
import Data.Text qualified as T

type Vertex = T.Text

parseLine :: T.Text -> (Vertex, (Vertex, Vertex))
parseLine s = (f key, (f left, f right))
  where
    (key, s') = cutOn '=' s
    (left, right) = cutOn ',' s'
    f = T.filter isAlpha

type DesertMap = Map Vertex (Vertex, Vertex)

-- L or R
type Step = Char

-- the ex. LLRRRLRRL string provided in input
type Directions = [Step]

parseInput :: T.Text -> (DesertMap, Directions)
parseInput s = (desertMap, direction)
  where
    s1 : s2 = T.lines s
    desertMap = fromList . map parseLine . filter (not . T.null) $ s2
    direction = T.unpack . T.strip $ s1

-- list of vertex visited, generated by following directions on a map
trace :: DesertMap -> Directions -> Vertex -> [Vertex]
trace m p0 start = scanl nextVert start (cycle p0)
  where
    nextVert v 'L' = fst $ m ! v
    nextVert v 'R' = snd $ m ! v

part1 :: (DesertMap, Directions) -> Int
part1 (desertMap, directions) = length . takeWhile (/= "ZZZ") . trace' $ "AAA"
  where
    trace' = trace desertMap directions

endsWithA = T.isSuffixOf "A"

endsWithZ = T.isSuffixOf "Z"

-- N.B. the AoC problem words this as "a ghost follows all paths starting at ??A", reword to talk about multiple ghosts just names varaible names eaiser
part2 :: (DesertMap, Directions) -> Int
part2 (desertMap, directions) = foldl lcm 1 . map (length . takeWhile (not . endsWithZ) . trace') $ ghosts
  where
    trace' = trace desertMap directions
    ghosts = [v | v <- keys desertMap, endsWithA v]

main = solveWithInput p1 p2
  where
    p1 = part1 . parseInput
    p2 = part2 . parseInput